---
namespace: sshfs-system

resources:
  - namespace.yaml
  - csi-controller-rbac.yaml
  - csi-controller-sshfs.yaml
  - csi-nodeplugin-rbac.yaml
  - csi-nodeplugin-sshfs.yaml
  - csi-sshfs-storageclass.yaml
